# fly.toml app configuration file generated for logbook-sample-electric on 2024-01-19T13:55:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "logbook-sample-electric"
primary_region = "yyz"

[build]
  image = "electricsql/electric:0.9.0"

[env]
  AUTH_MODE = "insecure"
  DATABASE_URL = "postgresql://postgres:rlVuNfBLtzMVhKXt@db.phfmqkjwzdjwtntvbsvq.supabase.co:5432/postgres"
  ELECTRIC_WRITE_TO_PG_MODE = "direct_writes"
  PG_PROXY_PASSWORD = "proxyPassword"
  LOG_LEVEL = "debug"

[http_service]
  internal_port = 5133
  force_https = true

  [[http_service.checks]]
    interval = "10s"
    timeout = "1s"
    grace_period = "20s"
    method = "GET"
    path = "/api/status"

[[services]]
  protocol = "tcp"
  internal_port = 65432

  [[services.ports]]
    port = 65432
    handlers = ["pg_tls"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
