-- AlterTable
ALTER TABLE "api_key" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "daily_log" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "daily_log_item" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "feedback" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "file" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "file_property" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "file_property_value" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "image" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "location_entry" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "project" ALTER COLUMN "due_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "project_property" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "project_property_value" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "task" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "task_property" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "task_property_value" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "task_status" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "tenant" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "tenant_user" ALTER COLUMN "invite_sent_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "time_block" ALTER COLUMN "range_start_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "range_end_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "timer_start_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "timer_end_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "user_task" ALTER COLUMN "archived_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "server_updated_at" SET DATA TYPE TIMESTAMPTZ;
